### ISSUE TITLE
Any way to use wildcard in config file?

### ISSUE THREAD

**Issue by l0ser140** [xolox/python-rotate-backups#10]
I want to use something like this in my configs. Can I somehow do it?
```
[/backups/*/]
hourly = 24
daily = 7
weekly = 4
monthly = 12
```

**Comment by xolox** [comment]
Hi and thanks for the feedback. This is possible as of [version 5.2](https://github.com/xolox/python-rotate-backups/blob/master/CHANGELOG.rst#release-5-2-2018-04-27) that was just released.
