### ISSUE TITLE
Prevent littering the system log

### ISSUE THREAD

**Issue by rdiez** [xolox/python-rotate-backups#20]
First of all, many thanks for your excellent script.

The documentation states: "Log messages are saved to the system log"

Can you provide an option to stop littering the system log? I am running the script in an automated fashion, and I am keeping the console output in a separate place, in case I need to look at it. 

Unfortunately, there does not seem to be way to stop rotate-backup from writing to the system log. That is a lot of unnecessary messages to ignore.

**Comment by xolox** [comment]
Hi and thanks for the feedback. I've just released [rotate-backups 7.1](https://rotate-backups.readthedocs.io/en/latest/changelog.html#release-7-1-2020-02-13) which makes it possible to disable system logging using the new `rotate-backups --syslog=false` option. I hope this helps 😊.

**Comment by rdiez** [comment]
Many thanks!
