### ISSUE TITLE
[feature] span "hourly" preserver even over days period, etc...

### ISSUE THREAD

**Issue by epcim** [xolox/python-rotate-backups#3]
An example, keep 8 hourly backups, keep 4 days backups.

Today, it keep 8 backups created "today" and 1 for each of previous 4 days.

In case, I will create only 4 backups today I might have been interested still to keep additional backups from previous day (ie: like 8 hourly backups would not be affected by today timestamp)

**Comment by xolox** [comment]
Hi Petr and thanks again for the feedback. I just released rotate-backups version 3.1 which adds support for a relaxed rotation mode (as you suggested) using the `rotate-backups --relaxed` option. I'm pretty sure this resolves the problem you reported in #2 so I'm closing this issue now, but if you find any problems with the new feature then feel free to reopen this issue or open a new one.
