### ISSUE TITLE
Fails to work on macOS 

### ISSUE THREAD

**Issue by paulgessinger** [xolox/python-rotate-backups#6]
Your tool works flawlessly on my linux box, however I wanted to make use of it on my MacBook, but I run into a problem.

You call stat [here](https://github.com/xolox/python-rotate-backups/blob/b6daf3e500d118a54612b3beda2be01c903a8722/rotate_backups/__init__.py#L623), and that causes a problem on macOS, since the CLI is different here. 

I'm not sure if this is the only issue preventing it from working. Is there maybe a way to get the operating system from the executor to try and prevent this issue?

Thanks for making this, btw

**Comment by xolox** [comment]
Hi Paul and thanks for the feedback! I just released version 4.3 which implements/restores Mac OS X compatibility. I've also configured Travis CI to run the test suite on Mac OS X to ensure that I don't inadvertently break compatibility later on.
