### ISSUE TITLE
Deletion not expected

### ISSUE THREAD

**Issue by Klabuser** [xolox/python-rotate-backups#7]
Hi !

Version : 4.3

I encountered a behaviour I couldn't understand. This is my config file :

```
[/home/backup/data/mysql/production/scrap/fr/done]
relaxed = yes
include = '*.xbstream'
weekly = 3
monthly = 2
yearly = always
ionice = idle
```

And this is the behaviour rotate-backups had when launched :

```
Sep 27 12:04:02 backup-0001 rotate-backups[19632]: INFO Scanning /home/backup/data/mysql/production/scrap/fr/done for backups ..
Sep 27 12:04:02 backup-0001 rotate-backups[19632]: INFO Found 7 timestamped backups in /home/backup/data/mysql/production/scrap/fr/done.
Sep 27 12:04:02 backup-0001 rotate-backups[19632]: INFO Preserving /home/backup/data/mysql/production/scrap/fr/done/2017-01-13:22-24-57.xbstream (matches 'yearly' retention period) ..
Sep 27 12:04:02 backup-0001 rotate-backups[19632]: INFO Deleting /home/backup/data/mysql/production/scrap/fr/done/2017-05-17-mc_log_range ..
Sep 27 12:04:03 backup-0001 rotate-backups[19632]: INFO Deleting /home/backup/data/mysql/production/scrap/fr/done/2017-05-17-mc_log_range.tar.gz ..
Sep 27 12:04:03 backup-0001 rotate-backups[19632]: INFO Preserving /home/backup/data/mysql/production/scrap/fr/done/2017-08-04:04-45-05.xbstream (matches 'monthly' retention period) ..
Sep 27 12:04:03 backup-0001 rotate-backups[19632]: INFO Preserving /home/backup/data/mysql/production/scrap/fr/done/2017-09-09:19-48-41.xbstream (matches 'weekly' and 'monthly' retention periods) ..
Sep 27 12:04:03 backup-0001 rotate-backups[19632]: INFO Preserving /home/backup/data/mysql/production/scrap/fr/done/2017-09-20:07-17-24.xbstream (matches 'weekly' retention period) ..
Sep 27 12:04:03 backup-0001 rotate-backups[19632]: INFO Preserving /home/backup/data/mysql/production/scrap/fr/done/2017-09-27-mc_log_range (matches 'weekly' retention period) ..
```

The folder 2017-05-17-mc_log_range and the file 2017-05-17-mc_log_range.tar.gz were deleted even if they don't match the pattern '*.xbstream' defined in the config file.

Am I doing something wrong ?

**Comment by ernstki** [comment]
I'm seeing a similar issue, where I turned `rotate-backups` loose on a directory full of `.tar.bz2` and `.sql.gz` files, with different base names, but with the same ISO 8601-style timestamps, and one of the files (`owncloud-sqldump_YYYY-MM-DD.sql.gz`) is being indiscriminately deleted while the other set of files (`owncloud-data_YYYY-MM-DD.tar.bz2`) is being properly rotated.

```
[owncloud_backups]$ rotate-backups --dry-run --daily=7 --weekly=4 --monthly=6 --yearly=2 .
<snipped> Performing a dry run (because of --dry-run option) ..
<snipped> Scanning /path/to/owncloud_backups for backups ..
<snipped> Found 12 timestamped backups in /var/adm/owncloud_backups.
<snipped> Preserving /path/to/owncloud-data_2017-06-06.tar.bz2 (matches 'monthly' and 'yearly' retention periods) ..
<snipped> Preserving /path/to/owncloud-data_2017-09-22.tar.bz2 (matches 'weekly' and 'monthly' retention periods) ..
<snipped> Preserving /path/to/owncloud-data_2017-09-25.tar.bz2 (matches 'weekly' retention period) ..
<snipped> Deleting /path/to/owncloud-data_2017-09-28.tar.bz2 ..
<snipped> Preserving /path/to/owncloud-data_2017-09-29.tar.bz2 (matches 'daily' retention period) ..
<snipped> Preserving /path/to/owncloud-data_2017-09-30.tar.bz2 (matches 'daily' retention period) ..
<snipped> Preserving /path/to/owncloud-data_2017-10-01.tar.bz2 (matches 'daily' and 'monthly' retention periods) ..
<snipped> Preserving /path/to/owncloud-data_2017-10-02.tar.bz2 (matches 'daily' and 'weekly' retention periods) ..
<snipped> Preserving /path/to/owncloud-data_2017-10-03.tar.bz2 (matches 'daily' retention period) ..
<snipped> Preserving /path/to/owncloud-data_2017-10-04.tar.bz2 (matches 'daily' retention period) ..
<snipped> Preserving /path/to/owncloud-data_2017-10-05.tar.bz2 (matches 'daily' retention period) ..
<snipped> Deleting /path/to/owncloud-sqldump_2017-10-05.sql.gz ..
```

Naturally, I'm not sore about the files being deleted (there are _ample_ warnings about using `--dry-run` in the documentation), I'm just curious about the source for this surprising behavior.

**Comment by xolox** [comment]
Hi @Klabuser and thanks for the feedback. Looking at your configuration file I notice two problems:

1. It contains the option name ``include`` but rotate-backups is expecting ``include-list`` instead.
2. The pattern is quoted in strings but rotate-backups is expecting a literal pattern (without the quotes).

This made me realize that the ``include-list`` and ``exclude-list`` weren't documented anywhere, so in b150a239bffc7c8a2bcf3559248dd6861e18bca8 I documented all of the supported configuration file options and their expected values (e.g. that the patterns shouldn't be quoted). This information is now available in the [online documentation](https://rotate-backups.readthedocs.io/en/latest/readme.html#supported-configuration-options).

I'm going to close this issue now because the actual include/exclude list processing is working fine, it was just the documentation that was insufficient.
